# Generated by Django 6.0.8 on 2026-08-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(choices=[('windows', 'Windows'), ('android', 'Android')], max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorOverheadSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('backend_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_percent', models.FloatField()),
                ('memory_bytes', models.BigIntegerField()),
                ('memory_percent', models.FloatField()),
                ('read_bytes_per_second', models.FloatField(blank=True, null=True)),
                ('write_bytes_per_second', models.FloatField(blank=True, null=True)),
                ('sample_duration_ms', models.FloatField()),
                ('thread_count', models.PositiveIntegerField(blank=True, null=True)),
                ('handle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('network_socket_count', models.PositiveIntegerField(blank=True, null=True)),
                ('host_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_overhead_samples', to='telemetry.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['host_device', 'timestamp'], name='overhead_device_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('memory_in_use_bytes', models.BigIntegerField()),
                ('memory_available_bytes', models.BigIntegerField()),
                ('pagefile_percent', models.FloatField(blank=True, null=True)),
                ('disk_percent', models.FloatField(blank=True, null=True)),
                ('disk_used_bytes', models.BigIntegerField(blank=True, null=True)),
                ('disk_free_bytes', models.BigIntegerField(blank=True, null=True)),
                ('disk_read_bytes_per_second', models.FloatField(blank=True, null=True)),
                ('disk_write_bytes_per_second', models.FloatField(blank=True, null=True)),
                ('network_download_bytes_per_second', models.FloatField(blank=True, null=True)),
                ('network_upload_bytes_per_second', models.FloatField(blank=True, null=True)),
                ('process_count', models.PositiveIntegerField(blank=True, null=True)),
                ('top_cpu_process_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('top_cpu_process_name', models.CharField(blank=True, max_length=260)),
                ('top_cpu_process_percent', models.FloatField(blank=True, null=True)),
                ('top_memory_process_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('top_memory_process_name', models.CharField(blank=True, max_length=260)),
                ('top_memory_process_bytes', models.BigIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_samples', to='telemetry.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='telemetry_device_time_idx')],
            },
        ),
    ]
